### ISSUE TITLE
Object initializer instead of properties initialization

### ISSUE THREAD

**Issue by KvanTTT** [dj-raphael/DtoMapping#2]
I mean use the following code:

``` csharp
var itemDto = new DataTransferObject.UserDto
{
    UserId = item.UserId,
    Username = item.Login,
    Created = item.Created,
    Email = item.Email
};
```

instead of:

``` csharp
var itemDto = new DataTransferObject.UserDto ();
    itemDto.UserId = item.UserId;
    itemDto.Username = item.Login;
    itemDto.Created = item.Created;
    itemDto.Email = item.Email;
```

It can be additional setting in MapHelper.tt

**Comment by dj-raphael** [comment]
Initially it was, but when we needed map to ObservableRangeCollenction it had rewritten.
See [MappingExtension.g.cs:L67](https://github.com/dj-raphael/DtoMapping/blob/master/ConsoleApplicationParceAttribute/T4%20Folder/MappingExtension.g.cs#L67)
But this generated code, what difference would it look like?
Object initializers are just syntactic sugar, in your compiled assembly IL they translate into separate statements, check it on ILSpy.

**Comment by KvanTTT** [comment]
Is it possible to map ObservableRangeCollenction by usual way and other objects by object initializer? But you are right: it is not important feature.

**Comment by dj-raphael** [comment]
ObservableRangeCollenction is readonly in each ViewModels in our projects.
